### ISSUE TITLE
feature Animation Editor Component

### ISSUE THREAD

**Issue by Sythe2o0** [craftyjs/craftyjs.github.com#74]
This is more of a tool than a component, but I've been working on it recently and plan on putting a good amount more work into it, so I thought it'd be cool to add to the Components list at http://craftyjs.com/components/.

It's a graphical editor for sprite sheets' animations, so you can preview animations selected frame-by-frame from a sprite sheet, adjust animation speed, etc, and then generate a component with those reels and a json object to load that sprite sheet. Still a bit unstable-- no error messages yet, for example, and there's soft limit on sprite sheet size and animation length.

[Link!](https://github.com/Sythe2o0/CraftyAnimationEditor)

**Comment by mucaho** [comment]
Thanks, sounds great! Added via 354fc9596c91de3b373752c4b32956a9cf3378b2
